open_update = True
open_use_old_result = True
source_file = "G:/GitHub/SCXSVIP/Guovin-TV/moban.txt"
final_file = "result.txt"
favorite_list = ['CCTV-1', 'CCTV-2', 'CCTV-3', 'CCTV-4', 'CCTV-5', 'CCTV-5+', 'CCTV-6', 'CCTV-7', 'CCTV-8', 'CCTV-9', 'CCTV-10', 'CCTV-11', 'CCTV-12', 'CCTV-13', 'CCTV-14', 'CCTV-15', 'CCTV-16', 'CCTV-17', '重庆卫视', '重庆新闻', '浙江卫视', '湖南卫视', '广东卫视', '凤凰卫视', '翡翠台']
open_online_search = True
favorite_page_num = 5
default_page_num = 3
urls_limit = 10
open_driver = True
open_proxy = True
open_keep_all = True
open_sort = True
response_time_weight = 0.5
resolution_weight = 0.5
recent_days = 15
ipv_type = "ipv4"
domain_blacklist = ['epg.pw']
url_keywords_blacklist = []
open_subscribe = True
subscribe_urls = ['https://m3u.ibert.me/txt/fmml_dv6.txt', 'https://g.3344550.xyz/https://raw.githubusercontent.https://g.33445500.xyz/https://raw.githubusercontent.com/pxiptv/live/main/iptv.txt', 'https://g.3344550.xyz/https://raw.githubusercontent.com/pxiptv/TV/main/test.txt', 'https://g.3344550.xyz/https://raw.githubusercontent.com/ssili126/tv/main/itvlist.txt', 'https://m3u.ibert.me/txt/fmml_dv6.txt', 'https://m3u.ibert.me/txt/ycl_iptv.txt', 'https://m3u.ibert.me/txt/y_g.txt', 'https://m3u.ibert.me/txt/o_cn.txt', 'https://m3u.ibert.me/txt/j_iptv.txt']
open_multicast = True
region_list = ['all']
